export { default as Navbar } from "./Navbar";
export { default as HeaderCarousel } from "./HeaderCarousel";
export { default as Stories } from "./Stories";
export { default as YourRide } from "./YourRide";
export { default as TestRideForm } from "./TestRideForm";
export { default as ProductMenu } from "./ProductMenu";
export { default as ImageGallery } from "./ImageGallery";
export { default as Detailstab } from "./DetailsTab";
export { default as Hero } from "./Hero";
